// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// RUN: %clang_cc1 -Werror -Wno-atomic-alignment -triple powerpc64le-linux-gnu \
// RUN:   -target-cpu pwr8 -emit-llvm -o - %s | FileCheck %s \
// RUN:   --check-prefixes=PPC64,PPC64-QUADWORD-ATOMICS
// RUN: %clang_cc1 -Werror -Wno-atomic-alignment -triple powerpc64le-linux-gnu \
// RUN:   -emit-llvm -o - %s | FileCheck %s \
// RUN:   --check-prefixes=PPC64,PPC64-NO-QUADWORD-ATOMICS
// RUN: %clang_cc1 -Werror -Wno-atomic-alignment -triple powerpc64-unknown-aix \
// RUN:   -target-cpu pwr7 -emit-llvm -o - %s | FileCheck %s \
// RUN:   --check-prefixes=PPC64,PPC64-NO-QUADWORD-ATOMICS
// RUN: %clang_cc1 -Werror -Wno-atomic-alignment -triple powerpc64-unknown-aix \
// RUN:   -target-cpu pwr8 -emit-llvm -o - %s | FileCheck %s \
// RUN:   --check-prefixes=PPC64,PPC64-NO-QUADWORD-ATOMICS
// RUN: %clang_cc1 -Werror -Wno-atomic-alignment -triple powerpc64-unknown-aix \
// RUN:   -mabi=quadword-atomics -target-cpu pwr8 -emit-llvm -o - %s | \
// RUN:   FileCheck %s --check-prefixes=PPC64,PPC64-QUADWORD-ATOMICS


typedef struct {
  char x[16];
} Q;

typedef _Atomic(Q) AtomicQ;

typedef __int128_t int128_t;

Q test_load(AtomicQ *ptr) {
  // expected-no-diagnostics
  return __c11_atomic_load(ptr, __ATOMIC_ACQUIRE);
}

void test_store(Q val, AtomicQ *ptr) {
  // expected-no-diagnostics
  __c11_atomic_store(ptr, val, __ATOMIC_RELEASE);
}

void test_add(_Atomic(int128_t) *ptr, int128_t x) {
  // expected-no-diagnostics
  __c11_atomic_fetch_add(ptr, x, __ATOMIC_RELAXED);
}

Q test_xchg(AtomicQ *ptr, Q new) {
  // expected-no-diagnostics
  return __c11_atomic_exchange(ptr, new, __ATOMIC_SEQ_CST);
}

int test_cmpxchg(AtomicQ *ptr, Q *cmp, Q new) {
  // expected-no-diagnostics
  return __c11_atomic_compare_exchange_strong(ptr, cmp, new, __ATOMIC_SEQ_CST, __ATOMIC_RELAXED);
}

int test_cmpxchg_weak(AtomicQ *ptr, Q *cmp, Q new) {
  // expected-no-diagnostics
  return __c11_atomic_compare_exchange_weak(ptr, cmp, new, __ATOMIC_SEQ_CST, __ATOMIC_RELAXED);
}

int is_lock_free() {
  AtomicQ q;
 // expected-no-diagnostics
  return __c11_atomic_is_lock_free(sizeof(q));
}
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// PPC64: {{.*}}
// PPC64-NO-QUADWORD-ATOMICS: {{.*}}
// PPC64-QUADWORD-ATOMICS: {{.*}}
