; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple arm64-apple-ios -mattr +cmpbr -verify-machineinstrs -o - < %s | FileCheck %s

define void @cbge_out_of_upper_bound(i32 %a)  {
; CHECK-LABEL: cbge_out_of_upper_bound:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    mov w8, #71 ; =0x47
; CHECK-NEXT:    cbge w0, w8, LBB0_2
; CHECK-NEXT:  ; %bb.1: ; %if.end
; CHECK-NEXT:    ret
; CHECK-NEXT:  LBB0_2: ; %if.then
; CHECK-NEXT:    brk #0x1
entry:
  %cmp = icmp sgt i32 %a, 70
  br i1 %cmp, label %if.then, label %if.end

if.then:
  tail call void @llvm.trap()
  unreachable

if.end:
  ret void
}

define void @cbge_out_of_lower_bound(i32 %a)  {
; CHECK-LABEL: cbge_out_of_lower_bound:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    mov w8, #-10 ; =0xfffffff6
; CHECK-NEXT:    cbge w0, w8, LBB1_2
; CHECK-NEXT:  ; %bb.1: ; %if.end
; CHECK-NEXT:    ret
; CHECK-NEXT:  LBB1_2: ; %if.then
; CHECK-NEXT:    brk #0x1
entry:
  %cmp = icmp sge i32 %a, -10
  br i1 %cmp, label %if.then, label %if.end

if.then:
  tail call void @llvm.trap()
  unreachable

if.end:
  ret void
}

; This should trigger a register swap.
define void @cble_out_of_lower_bound(i32 %a)  {
; CHECK-LABEL: cble_out_of_lower_bound:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    mov w8, #-10 ; =0xfffffff6
; CHECK-NEXT:    cbhs w8, w0, LBB2_2
; CHECK-NEXT:  ; %bb.1: ; %if.end
; CHECK-NEXT:    ret
; CHECK-NEXT:  LBB2_2: ; %if.then
; CHECK-NEXT:    brk #0x1
entry:
  %cmp = icmp ule i32 %a, -10
  br i1 %cmp, label %if.then, label %if.end

if.then:
  tail call void @llvm.trap()
  unreachable

if.end:
  ret void
}
